x-kafka-common: &kafka-common
  image: 'bitnami/kafka:3.3.2'
  ports:
    - "9092/tcp"
    - "9093/tcp"
  healthcheck:
    test: "bash -c 'printf \"\" > /dev/tcp/127.0.0.1/9092; exit $$?;'"
    interval: 5s
    timeout: 10s
    retries: 3
    start_period: 30s
  restart: on-failure

x-kafka-env-common: &kafka-env-common
  KAFKA_KRAFT_CLUSTER_ID: 3WaQdTLLSJaCfQor3bUAXA
  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093,1@kafka-1:9093
  KAFKA_CFG_PROCESS_ROLES: controller,broker
  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093

services:
  kafka-0:
    container_name: kafka-0
    <<: *kafka-common
    environment:
      <<: *kafka-env-common
      KAFKA_CFG_NODE_ID: 0
    volumes:
      - kafka_0_data:/bitnami/kafka

  kafka-1:
    container_name: kafka-1
    <<: *kafka-common
    environment:
      <<: *kafka-env-common
      KAFKA_CFG_NODE_ID: 1
    volumes:
      - kafka_1_data:/bitnami/kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    environment:
      AUTH_TYPE: "LOGIN_FORM"
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: iqosxapp
      KAFKA_CLUSTERS_0_NAME: iqos-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9092,kafka-1:9092
    depends_on:
      - kafka-0
      - kafka-1
    ports:
      - '8080:8080/tcp'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8080 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 30s

iqos-xapp:
  container_name: iqos-xapp
  image: muriloavlis/iqos-xapp:latest
  depends_on:
    - kafka-0
    - kafka-1
  ports:
    - "36422/sctp"

volumes:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local