#IQoS xApp from UFPA

replicaCount: 1

image:
  repository: muriloavlis/iqos-xapp
  pullPolicy: IfNotPresent
  tag: "v1.0.0-dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 80
  grpc:
    port: 5150
  gnmi:
    port: 9339
  exporter:
    port: 7001
    nodePort:
      enabled: false
      port: 31701

config:
  onos:
    # e2tEndpoint: "onos-e2t:5150" (TODO)
    # kpmVersion: "v2"
  iqosXapp:
    configJson:
      reportPeriod:
        interval: 1000 # 1000 ms ??
        granularity: 1000 # 1000 ms ??
      slices: # (TODO)

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true 

ingress:
  enabled: true

autoscaling:
  enabled: false
  minReplicas: 1

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}