#IQoS xApp from UFPA

replicaCount: 1

image:
  repository: muriloavlis/iqos-xapp
  pullPolicy: Always
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  grpc:
    port: 5150
  gnmi:
    port: 9339

config:
  onos:
    # e2tEndpoint: "onos-e2t:5150" (TODO)
    # kpmVersion: "v2"
  iqosXapp:
    configJson:
      reportPeriod:
        interval: 1000 # 1000 ms ??
        granularity: 1000 # 1000 ms ??
      slices: # (TODO)

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: false

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}